### ISSUE TITLE
Widget News and Widget Bookmarks not working

### ISSUE THREAD

**Issue by damoosenrw** [fjies/dashboard#112]
Hello,

I just installed your dashboard app for oc8.

I activated the news and bookmarks widget. The news widget told me, I had to activate the news app. Weird, because it is activated.

In the bookmarks widget, no bookmarks are displayed.

But the weirdest thing is, that now when I navigate to the dashboard, the first three widgets I activated are displayed. In the lower left corner the "loading" symbol never stops running.

The oc logs show the following error:

Fatal 	

index 	

Exception: {"Message":"Could not resolve ItemBusinessLayer! Class ItemBusinessLayer does not exist","Code":0,"Trace":"#0 \/homepages\/22\/d19691424\/htdocs\/oc\/lib\/private\/appframework\/utility\/simplecontainer.php(93): OC\\AppFramework\\Utility\\SimpleContainer->resolve('ItemBusinessLay...')\n#1 \/homepages\/22\/d19691424\/htdocs\/oc\/apps\/dashboard\/widgets\/news\/newscontroller.php(124): OC\\AppFramework\\Utility\\SimpleContainer->query('ItemBusinessLay...')\n#2 \/homepages\/22\/d19691424\/htdocs\/oc\/apps\/dashboard\/widgets\/news\/newscontroller.php(137): OCA\\Dashboard\\Widgets\\News\\NewsController->getNewsApp()\n#3 \/homepages\/22\/d19691424\/htdocs\/oc\/apps\/dashboard\/widgets\/news\/newscontroller.php(41): OCA\\Dashboard\\Widgets\\News\\NewsController->getNews()\n#4 \/homepages\/22\/d19691424\/htdocs\/oc\/apps\/dashboard\/widgets\/widgettemplate.php(51): OCA\\Dashboard\\Widgets\\News\\NewsController->getData()\n#5 \/homepages\/22\/d19691424\/htdocs\/oc\/apps\/dashboard\/controller\/widgetcontroller.php(63): OCA\\Dashboard\\Widgets\\WidgetTemplate->getHtml(Object(OCA\\Dashboard\\Widgets\\News\\NewsController))\n#6 [internal function]: OCA\\Dashboard\\Controller\\WidgetController->getComplete('news-1')\n#7 \/homepages\/22\/d19691424\/htdocs\/oc\/lib\/private\/appframework\/http\/dispatcher.php(158): call_user_func_array(Array, Array)\n#8 \/homepages\/22\/d19691424\/htdocs\/oc\/lib\/private\/appframework\/http\/dispatcher.php(86): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Dashboard\\Controller\\WidgetController), 'getComplete')\n#9 \/homepages\/22\/d19691424\/htdocs\/oc\/lib\/private\/appframework\/app.php(97): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Dashboard\\Controller\\WidgetController), 'getComplete')\n#10 \/homepages\/22\/d19691424\/htdocs\/oc\/lib\/private\/appframework\/routing\/routeactionhandler.php(44): OC\\AppFramework\\App::main('WidgetControlle...', 'getComplete', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#11 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#12 \/homepages\/22\/d19691424\/htdocs\/oc\/lib\/private\/route\/router.php(250): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#13 \/homepages\/22\/d19691424\/htdocs\/oc\/lib\/base.php(763): OC\\Route\\Router->match('\/apps\/dashboard...')\n#14 \/homepages\/22\/d19691424\/htdocs\/oc\/index.php(36): OC::handleRequest()\n#15 {main}","File":"\/homepages\/22\/d19691424\/htdocs\/oc\/lib\/private\/appframework\/utility\/simplecontainer.php","Line":79}

**Comment by fjies** [comment]
which news-app-version do you use?

**Comment by damoosenrw** [comment]
The current one: 5.2.7

**Comment by fjies** [comment]
version 5 is not yet supported.
Version 4 is working.

I'm in developing for version 5...

Bookmarks had an error, fixed it with the new commits.
